# Generated by Django 6.1 on 2026-08-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone_verified',
            field=models.BooleanField(default=True, verbose_name='Номер телефона подтвержден'),
        ),
    ]
