# Generated by Django 6.1 on 2026-08-25 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'db_table': 'schedule_days',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='schedule.scheduleday', verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Окошко для записи',
                'verbose_name_plural': 'Окошки для записи',
                'db_table': 'appointment_slots',
                'ordering': ('schedule_day__date', 'start_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleday',
            constraint=models.UniqueConstraint(fields=('master', 'date'), name='unique_schedule_day_per_master'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.UniqueConstraint(fields=('schedule_day', 'start_time', 'end_time'), name='unique_appointment_slot_period_per_day'),
        ),
    ]
