# Generated by Django 6.1 on 2026-08-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_slots', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Свободно'), (2, 'Клиент записан'), (3, 'Выполнено'), (0, 'Отменено / клиент не пришёл')], default=1, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('status', 1)), models.Q(('client__isnull', False), ('status__in', (2, 3, 0))), _connector='OR'), name='appointment_slot_status_matches_client'),
        ),
    ]
