# Generated by Django 6.1 on 2026-09-04 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_appointmentslot_client_appointmentslot_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_day_templates', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Шаблон рабочего дня',
                'verbose_name_plural': 'Шаблоны рабочих дней',
                'db_table': 'schedule_day_templates',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleDayTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_reusable', models.BooleanField(default=False, verbose_name='Сохранено для повторного использования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_day_template_slots', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='schedule.scheduledaytemplate', verbose_name='Шаблон рабочего дня')),
            ],
            options={
                'verbose_name': 'Шаблон окошка',
                'verbose_name_plural': 'Шаблоны окошек',
                'db_table': 'schedule_day_template_slots',
                'ordering': ('start_time', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='scheduledaytemplate',
            constraint=models.UniqueConstraint(fields=('master', 'name'), name='unique_schedule_day_template_name_per_master'),
        ),
        migrations.AddConstraint(
            model_name='scheduledaytemplateslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_day_template_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='scheduledaytemplateslot',
            constraint=models.UniqueConstraint(fields=('template', 'start_time', 'end_time'), name='unique_slot_period_per_schedule_day_template'),
        ),
        migrations.AddConstraint(
            model_name='scheduledaytemplateslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reusable', True)), fields=('master', 'name'), name='unique_reusable_slot_template_name_per_master'),
        ),
    ]
