# Generated by Django 6.1 on 2026-08-24 23:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Стоимость'),
        ),
    ]
