# Generated by Django 6.1 on 2026-08-25 06:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_services', '0002_alter_service_price'),
        ('clients', '0002_alter_client_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Выполненная услуга',
                'verbose_name_plural': 'Выполненные услуги',
                'db_table': 'completed_services',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_material_cost__isnull', True), ('estimated_material_cost__gte', 0), _connector='OR'), name='service_material_cost_non_negative'),
        ),
        migrations.AddField(
            model_name='completedservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_services', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='completedservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_services', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='completedservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_services', to='catalog_services.service', verbose_name='Услуга'),
        ),
        migrations.AddConstraint(
            model_name='completedservice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='completed_service_price_non_negative'),
        ),
    ]
