# Generated by Django 6.1 on 2026-08-22 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в международном формате, например +79991234567.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='Номер телефона')),
                ('phone_verified', models.BooleanField(default=True, verbose_name='Номер телефона подтвержден')),
                ('messenger_max_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID в MAX')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('master', 'phone'), name='unique_client_phone_per_master')],
            },
        ),
    ]
