# Generated by Django 6.1 on 2026-08-25 06:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date.today, message='Дата рождения не может быть в будущем.')], verbose_name='Дата рождения'),
        ),
    ]
