# Generated by Django 6.1 on 2026-08-25 06:05

from django.db import migrations


GLOBAL_EXPENSE_GROUP_NAMES = (
    "Расходники",
    "Покупка оборудования",
    "ТО оборудования",
)


def create_global_expense_groups(apps, schema_editor):
    expense_group = apps.get_model("expenses", "ExpenseGroup")

    for name in GLOBAL_EXPENSE_GROUP_NAMES:
        expense_group.objects.get_or_create(master_id=None, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_global_expense_groups,
            migrations.RunPython.noop,
        ),
    ]
