# Generated by Django 6.1 on 2026-08-25 06:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_create_global_expense_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroup',
            name='is_active',
        ),
        migrations.CreateModel(
            name='ExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_templates', to='expenses.expensegroup', verbose_name='Группа расходов')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_templates', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Шаблон расхода',
                'verbose_name_plural': 'Шаблоны расходов',
                'db_table': 'expense_templates',
                'ordering': ('group__name', 'amount'),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_template_amount_greater_than_zero')],
            },
        ),
    ]
